"""
Django settings for logersenegal project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-^gda*3#uhe6a6$lb#l23y*=_m-9%c&54(!pp*(rp_v%pn@^%gx')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ['logersenegal.com', 'www.logersenegal.com', 'localhost', '127.0.0.1']
SITE_URL = 'https://logersenegal.com'

CSRF_TRUSTED_ORIGINS = [
    'https://logersenegal.com',
    'https://www.logersenegal.com',
]


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'django.contrib.sites',
    
    # Third-party
    'rest_framework',
    'corsheaders',

    # Local apps
    'users',
    'logersn',
    'solvable',
    'chat',
    'ads',
    'drf_spectacular',
]

SITE_ID = 1

AUTH_USER_MODEL = 'users.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'logersenegal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'ads.context_processors.ads_processor',
                'solvable.context_processors.fraud_alerts_processor',
                'solvable.context_processors.system_alerts_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'logersenegal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME', 'gaak4328_loger_app'),
        'USER': os.environ.get('DB_USER', 'gaak4328_loger_app'), 
        'PASSWORD': os.environ.get('DB_PASSWORD', '5KMtFH-8kz3PgtJ'), 
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '3306'),
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES', NAMES 'utf8mb4'",
            'charset': 'utf8mb4',
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'users.validators.ComplexPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'Africa/Dakar'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Optimisation WhiteNoise (Version souple pour O2switch)
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# WhiteNoise sert les fichiers statiques (JS, CSS). 
# Pour un déploiement souple sur O2switch avec LiteSpeed, 
# on laisse Apache servir le dossier media physique directement.
WHITENOISE_INDEX_FILE = False

# STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

# Email Configuration (O2switch SMTP gratuit)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'mail.logersenegal.com'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_HOST_USER = 'solvable@logersenegal.com'
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_PASSWORD', '-P7GvVHJ2RmjnTG')
DEFAULT_FROM_EMAIL = 'Solvable Loger Sénégal <solvable@logersenegal.com>'
SERVER_EMAIL = 'solvable@logersenegal.com'

# Configuration FedaPay / DigitalH
# (Les paramètres MEDIA_URL et MEDIA_ROOT sont définis plus haut)

# Auth Settings
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'home'

JAZZMIN_SETTINGS = {
    "site_title": "Back-office Logersenegal",
    "site_header": "LOGERSENEGAL",
    "site_brand": "Administration Logersenegal",
    "welcome_sign": "Espace Opérateur Technique & Juridique",
    "copyright": "HDIGITAL - Logersenegal (Sénégal)",
    "search_model": ["users.User", "solvable.IncidentReport", "users.NILS_Profile"],
    "show_ui_builder": False,
    "icons": {
        "users.user": "fas fa-user-tie",
        "users.kycprofile": "fas fa-id-card-clip",
        "users.nils_profile": "fas fa-star-half-stroke",
        "solvable.rentalfiliation": "fas fa-file-contract",
        "solvable.paymenthistory": "fas fa-money-check-dollar",
        "solvable.incidentreport": "fas fa-gavel",
        "logersn.property": "fas fa-building",
        "logersn.propertyimage": "fas fa-images",
        "chat.conversation": "fas fa-comments",
        "chat.message": "fas fa-comment-dots",
    },
    "order_with_respect_to": ["users", "solvable", "logersn", "chat"],
    "default_icon_parents": "fas fa-folder-open",
    "default_icon_children": "fas fa-bullseye",
    "topmenu_links": [
        {"name": "Accueil Admin", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Statistiques Réelles", "url": "/admin/statistiques/", "permissions": ["auth.view_user"], "new_window": False},
    ],
    "related_modal_active": True,
}

JAZZMIN_UI_TWEAKS = {
    "theme": "flatly", 
    "navbar": "navbar-dark navbar-success",
    "sidebar": "sidebar-dark-success",
    "brand_colour": "navbar-success",
    "accent": "accent-success",
    "navbar_fixed": True,
    "sidebar_fixed": True,
    "sidebar_nav_child_indent": True,
    "button_classes": {
        "primary": "btn-success",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}
# REST Framework Config
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Solvable Loger Sénégal API',
    'DESCRIPTION': 'Documentation technique des services immobiliers de prestige par DigitalH.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# Sitemap & Domain
SITE_ID = 1

# --- CONFIGURATION LOCALE (ZÉRO CONFLIT) ---
# Ce bloc permet de surcharger les réglages (comme la BDD) sur le serveur
try:
    from .local_settings import *
except ImportError:
    pass

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- CACHE CONFIGURATION (Optimisation shared hosting O2switch) ---
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': os.path.join(BASE_DIR, 'tmp', 'django_cache'),
        'TIMEOUT': 3600, # 1 heure par défaut
    }
}

# --- SECURITY & HSTS (SEO & Trust) ---
if not DEBUG:
    # Rappel : SSL est actif sur le serveur (Cadenas OK)
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # Sécurité supplémentaire
    SECURE_HSTS_SECONDS = 15768000 # 6 mois
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'

# --- PWA CONFIGURATION ---
# PWA_APP_NAME = 'Solvable Sénégal'
# PWA_APP_SHORT_NAME = 'Solvable'
# PWA_APP_DESCRIPTION = "Plateforme d'Immobilier de Confiance au Sénégal"
# PWA_APP_THEME_COLOR = '#0b4629'
# PWA_APP_BACKGROUND_COLOR = '#ffffff'
# PWA_APP_DISPLAY = 'standalone'
# PWA_APP_SCOPE = '/'
# PWA_APP_ORIENTATION = 'any'
# PWA_APP_START_URL = '/'
# PWA_APP_STATUS_BAR_COLOR = 'default'
# PWA_APP_ICONS = [
#     {
#         'src': '/static/img/icon-192x192.png',
#         'sizes': '192x192'
#     },
#     {
#         'src': '/static/img/icon-512x512.png',
#         'sizes': '512x512'
#     }
# ]
# PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR, 'static', 'serviceworker.js')
