# Generated by Django 6.0.3 on 2026-04-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_cni_number_alter_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nils_profile',
            name='nils_type',
            field=models.CharField(choices=[('TENANT', 'Locataire'), ('LANDLORD', 'Bailleur'), ('AGENCY', 'Agence Immobilière'), ('BROKER', 'Courtier'), ('AGENT', 'Agent'), ('SUB_ADMIN', 'Sous-Administrateur DigitalH'), ('CUSTOMER_SUPPORT', 'Conseiller Client DigitalH')], default='TENANT', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('TENANT', 'Locataire'), ('LANDLORD', 'Bailleur'), ('AGENCY', 'Agence Immobilière'), ('BROKER', 'Courtier'), ('AGENT', 'Agent'), ('SUB_ADMIN', 'Sous-Administrateur DigitalH'), ('CUSTOMER_SUPPORT', 'Conseiller Client DigitalH')], default='TENANT', max_length=20, verbose_name='Statut du compte'),
        ),
    ]
