# Generated by Django 6.0.3 on 2026-04-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_nils_profile_nils_type_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='document_country',
            field=models.CharField(default='Togo', max_length=100, verbose_name='Pays de délivrance du document'),
        ),
    ]
