# Generated by Django 5.1.6 on 2026-04-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_is_solvable_solvencydocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='solvency_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='solvency_income_avg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='user',
            name='solvency_max_rent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_solvable',
            field=models.BooleanField(default=False),
        ),
    ]
