# Generated by Django 5.1.6 on 2026-04-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_solvency_expiry_date_user_solvency_income_avg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_preference',
            field=models.CharField(choices=[('SMS', 'SMS uniquement'), ('EMAIL', 'E-mail uniquement'), ('BOTH', 'SMS & E-mail')], default='BOTH', max_length=10, verbose_name='Préférence de notification'),
        ),
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='Lien personnalisé'),
        ),
    ]
