# Generated by Django 5.1.6 on 2026-04-25 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_notification_preference_user_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchlog',
            name='searcher',
        ),
        migrations.RemoveField(
            model_name='solvencydocument',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Biographie / Description'),
        ),
        migrations.AddField(
            model_name='user',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0, verbose_name="Années d'expérience"),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_solvable',
            field=models.BooleanField(default=False, verbose_name='Locataire Solvable'),
        ),
        migrations.DeleteModel(
            name='NILS_Profile',
        ),
        migrations.DeleteModel(
            name='SearchLog',
        ),
        migrations.DeleteModel(
            name='SolvencyDocument',
        ),
    ]
