# Generated by Django 6.0.4 on 2026-05-05 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_searchlog_searcher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, verbose_name='Numéro de téléphone'),
        ),
    ]
