# Generated by Django 6.0.3 on 2026-05-22 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_saas_active',
            field=models.BooleanField(default=False, verbose_name='Abonnement SaaS Agence Actif'),
        ),
    ]
