# Generated by Django 6.0.4 on 2026-05-24 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_user_is_saas_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='parent_agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_tenants', to=settings.AUTH_USER_MODEL, verbose_name='Agence parente'),
        ),
    ]
