# Generated by Django 6.0.4 on 2026-05-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_user_parent_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agency_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Adresse postale de l'agence"),
        ),
        migrations.AddField(
            model_name='user',
            name='agency_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Ville de l'agence"),
        ),
        migrations.AddField(
            model_name='user',
            name='agency_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name="Email officiel de l'agence"),
        ),
        migrations.AddField(
            model_name='user',
            name='agency_nif',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro NIF / Identifiant Fiscal'),
        ),
        migrations.AddField(
            model_name='user',
            name='agency_phone_landline',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Téléphone fixe'),
        ),
        migrations.AddField(
            model_name='user',
            name='agency_phone_mobile',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Téléphone mobile (Agence)'),
        ),
        migrations.AddField(
            model_name='user',
            name='agency_rccm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro RCCM / N° Entreprise'),
        ),
        migrations.AddField(
            model_name='user',
            name='agency_tagline',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Slogan ou spécialité de l'agence"),
        ),
        migrations.AddField(
            model_name='user',
            name='agency_website',
            field=models.URLField(blank=True, null=True, verbose_name="Site web de l'agence"),
        ),
    ]
