# Generated by Django 6.0.4 on 2026-05-26 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_saas_active',
            field=models.BooleanField(default=False, verbose_name='Abonnement SaaS Actif (Agence / Hôtel / Auberge)'),
        ),
    ]
