# Generated by Django 6.0.4 on 2026-05-26 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_user_is_saas_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='parent_hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_staff', to=settings.AUTH_USER_MODEL, verbose_name='Hôtel parent'),
        ),
    ]
