# Generated by Django 6.0.3 on 2026-05-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_user_parent_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('TENANT', 'Locataire'), ('LANDLORD', 'Bailleur'), ('AGENCY', 'Agence Immobilière'), ('BROKER', 'Démarcheur'), ('AGENT', 'Agent'), ('SUB_ADMIN', 'Sous-Administrateur DigitalH'), ('CUSTOMER_SUPPORT', 'Conseiller Client DigitalH'), ('HOTEL', 'Hôtel'), ('AUBERGE', "Auberge / Maison d'Hôtes")], default='TENANT', max_length=20, verbose_name='Statut du compte'),
        ),
    ]
