# Generated by Django 6.0.3 on 2026-05-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agency_latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='Latitude GPS'),
        ),
        migrations.AddField(
            model_name='user',
            name='agency_longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='Longitude GPS'),
        ),
        migrations.AddField(
            model_name='user',
            name='agency_neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Quartier de l'établissement"),
        ),
    ]
