# Generated by Django 5.1.6 on 2026-04-25 00:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logersn', '0022_add_property_alert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin (Optionnelle)')),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Loyer mensuel (FCFA)')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Dépôt de garantie (Caution)')),
                ('status', models.CharField(choices=[('PENDING', 'En attente de signature'), ('ACTIVE', 'Actif'), ('TERMINATED', 'Terminé'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20)),
                ('contract_pdf', models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='Contrat signé (PDF)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='landlord_leases', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='logersn.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_leases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bail',
                'verbose_name_plural': 'Baux',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name="Titre de l'incident")),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('priority', models.CharField(choices=[('LOW', 'Basse'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Haute'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Ouvert'), ('IN_PROGRESS', 'En cours'), ('RESOLVED', 'Résolu'), ('CLOSED', 'Fermé')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='management.lease')),
            ],
            options={
                'verbose_name': "Demande d'entretien",
                'verbose_name_plural': "Demandes d'entretien",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField(verbose_name='Période du')),
                ('period_end', models.DateField(verbose_name='Période au')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Montant dû')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Montant payé')),
                ('status', models.CharField(choices=[('UNPAID', 'Impayé'), ('PARTIAL', 'Partiel'), ('PAID', 'Payé')], default='UNPAID', max_length=20)),
                ('date_paid', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('receipt_pdf', models.FileField(blank=True, null=True, upload_to='receipts/', verbose_name='Quittance de loyer (PDF)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='management.lease')),
            ],
            options={
                'verbose_name': 'Paiement de Loyer',
                'verbose_name_plural': 'Paiements de Loyers',
                'ordering': ['-period_start'],
            },
        ),
    ]
