# Generated by Django 5.1.6 on 2026-04-25 02:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('ID_CARD', "Pièce d'identité (CNI/Passeport)"), ('EMPLOYMENT', "Attestation d'emploi"), ('PAYSLIP', 'Fiche de paie'), ('OLD_RECEIPT', 'Ancienne quittance'), ('OTHER', 'Autre document')], max_length=20)),
                ('file', models.FileField(upload_to='tenant_dossiers/%Y/%m/', verbose_name='Fichier')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Vérifié par Loger Togo')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Locataire',
                'verbose_name_plural': 'Documents Locataires',
            },
        ),
    ]
