# Generated by Django 5.1.6 on 2026-04-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_tenantdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='custom_contract_terms',
            field=models.TextField(blank=True, null=True, verbose_name='Clauses particulières (Personnalisation)'),
        ),
        migrations.AddField(
            model_name='lease',
            name='custom_header_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='En-tête personnalisé (ex: Agence Digitale)'),
        ),
    ]
