# Generated by Django 6.0.3 on 2026-05-22 22:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_lease_custom_contract_terms_lease_custom_header_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255, verbose_name='Nom complet')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('client_type', models.CharField(choices=[('TENANT', 'Locataire'), ('LANDLORD', 'Bailleur'), ('PARTNER', 'Partenaire'), ('OTHER', 'Autre')], default='TENANT', max_length=20)),
                ('status', models.CharField(choices=[('PROSPECT', 'Prospect'), ('ACTIVE', 'Actif'), ('INACTIVE', 'Inactif')], default='PROSPECT', max_length=20)),
                ('pipeline_stage', models.IntegerField(default=1, verbose_name='Étape de Pipeline (1-5)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes / Détails')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Client d'Agence",
                'verbose_name_plural': "Clients d'Agence",
                'ordering': ['-created_at'],
            },
        ),
    ]
