# Generated by Django 6.0.3 on 2026-05-22 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_agencyclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentpayment',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mode de paiement'),
        ),
        migrations.AddField(
            model_name='rentpayment',
            name='receipt_footer',
            field=models.TextField(blank=True, null=True, verbose_name='Pied de page personnalisé'),
        ),
        migrations.AddField(
            model_name='rentpayment',
            name='receipt_header',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='En-tête personnalisé'),
        ),
        migrations.AddField(
            model_name='rentpayment',
            name='receipt_logo',
            field=models.FileField(blank=True, null=True, upload_to='receipt_logos/', verbose_name='Logo de la quittance'),
        ),
    ]
