# Generated by Django 6.0.4 on 2026-05-23 03:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_rentpayment_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyclient',
            name='pipeline_stage',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Étape de Pipeline (1-5)'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Dépôt de garantie (Caution)'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='rent_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Loyer mensuel (FCFA)'),
        ),
        migrations.AlterField(
            model_name='rentpayment',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant dû'),
        ),
        migrations.AlterField(
            model_name='rentpayment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant payé'),
        ),
    ]
