# Generated by Django 6.0.3 on 2026-05-23 10:29

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_agencyclient_pipeline_stage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='payment_due_day',
            field=models.IntegerField(default=5, help_text='Jour limite de paiement dans le mois (ex: 5 pour payer avant le 5 du mois)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)], verbose_name="Jour d'échéance de paiement"),
        ),
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Titre du modèle')),
                ('content', models.TextField(help_text='Utilisez les balises de substitution : [LOCATAIRE], [PROPRIETAIRE], [BIEN], [LOYER], [CAUTION], [DATE_DEBUT], [DATE_FIN]', verbose_name='Contenu du contrat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modèle de contrat',
                'verbose_name_plural': 'Modèles de contrats',
                'ordering': ['-created_at'],
            },
        ),
    ]
