# Generated by Django 6.0.3 on 2026-05-23 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_lease_payment_due_day_contracttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leases', to='management.contracttemplate', verbose_name='Modèle de contrat'),
        ),
    ]
