# Generated by Django 6.0.4 on 2026-05-23 20:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_lease_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='is_signed_by_landlord',
            field=models.BooleanField(default=False, verbose_name='Signé par le bailleur/agence'),
        ),
        migrations.AddField(
            model_name='lease',
            name='is_signed_by_tenant',
            field=models.BooleanField(default=False, verbose_name='Signé par le locataire'),
        ),
        migrations.AddField(
            model_name='lease',
            name='landlord_otp',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Code OTP Bailleur'),
        ),
        migrations.AddField(
            model_name='lease',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de signature finale'),
        ),
        migrations.AddField(
            model_name='lease',
            name='tenant_otp',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Code OTP Locataire'),
        ),
        migrations.CreateModel(
            name='PropertyInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inventory_type', models.CharField(choices=[('IN', 'Entrée'), ('OUT', 'Sortie')], default='IN', max_length=5, verbose_name="Type d'état des lieux")),
                ('inventory_date', models.DateField(verbose_name="Date de l'état des lieux")),
                ('general_condition', models.CharField(choices=[('NEW', 'Neuf'), ('GOOD', 'Bon état'), ('FAIR', "État d'usage"), ('BAD', 'Mauvais état')], default='GOOD', max_length=10, verbose_name='État général')),
                ('details_json', models.TextField(help_text="Stockage JSON structuré des pièces et composants de l'état des lieux")),
                ('signature_tenant', models.TextField(blank=True, help_text='Signature en Base64 du locataire', null=True)),
                ('signature_agent', models.TextField(blank=True, help_text="Signature en Base64 de l'agent/bailleur", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='management.lease', verbose_name='Bail')),
            ],
            options={
                'verbose_name': 'État des lieux',
                'verbose_name_plural': 'États des lieux',
                'ordering': ['-inventory_date', '-created_at'],
            },
        ),
    ]
