# Generated by Django 6.0.3 on 2026-05-26 00:24

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_alter_contracttemplate_agency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=255, verbose_name='Nom complet du client')),
                ('client_phone', models.CharField(max_length=50, verbose_name='Téléphone')),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('client_id_card', models.CharField(blank=True, max_length=100, null=True, verbose_name="Pièce d'identité")),
                ('check_in', models.DateTimeField(verbose_name="Date/Heure d'arrivée")),
                ('check_out', models.DateTimeField(verbose_name='Date/Heure de départ')),
                ('status', models.CharField(choices=[('PENDING', 'Confirmée'), ('CHECKED_IN', 'Client Arrivé (Check-in)'), ('CHECKED_OUT', 'Client Parti (Check-out)'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=20)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Montant hébergement')),
                ('extra_charges', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Frais supplémentaires')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Montant payé')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mode de paiement')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes / Demandes spéciales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Réservation d'Hôtel",
                'verbose_name_plural': "Réservations d'Hôtel",
            },
        ),
        migrations.CreateModel(
            name='HotelChargeItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255, verbose_name='Libellé de la prestation (ex: Bière, Petit déj, Lessive)')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Prix unitaire (FCFA)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='management.hotelbooking')),
            ],
        ),
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=50, verbose_name='Numéro de chambre / Nom')),
                ('room_type', models.CharField(choices=[('SINGLE', 'Chambre Simple'), ('DOUBLE', 'Chambre Double'), ('TWIN', 'Chambre Twin'), ('SUITE', 'Suite'), ('DELUXE', 'Suite Deluxe'), ('DORMITORY', 'Dortoir')], default='SINGLE', max_length=20)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix par nuitée (FCFA)')),
                ('price_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix par heure (FCFA) - Optionnel')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('OCCUPIED', 'Occupée'), ('CLEANING', 'En cours de ménage'), ('MAINTENANCE', 'En maintenance')], default='AVAILABLE', max_length=20)),
                ('wifi', models.BooleanField(default=False)),
                ('air_conditioning', models.BooleanField(default=False)),
                ('minibar', models.BooleanField(default=False)),
                ('tv', models.BooleanField(default=False)),
                ('safe', models.BooleanField(default=False)),
                ('balcony', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Chambre d'Hôtel",
                'verbose_name_plural': "Chambres d'Hôtel",
                'unique_together': {('hotel', 'room_number')},
            },
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='management.hotelroom'),
        ),
    ]
