# Generated by Django 6.0.4 on 2026-05-26 01:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_hotelbooking_hotelchargeitem_hotelroom_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name="Date/Heure d'ouverture")),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Date/Heure de clôture')),
                ('initial_cash', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Fonds de caisse initial (FCFA)')),
                ('actual_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Espèces réelles comptées (FCFA)')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Shift clôturé')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes / Observations de passation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_shifts', to=settings.AUTH_USER_MODEL, verbose_name='Établissement')),
                ('receptionist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptionist_shifts', to=settings.AUTH_USER_MODEL, verbose_name='Réceptionniste')),
            ],
            options={
                'verbose_name': 'Shift de Caisse',
                'verbose_name_plural': 'Shifts de Caisse',
                'ordering': ['-start_time'],
            },
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='management.hotelshift', verbose_name='Shift de caisse'),
        ),
    ]
