# Generated by Django 6.0.3 on 2026-05-27 01:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_hotelshift_hotelbooking_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant (FCFA)')),
                ('payment_method', models.CharField(max_length=50, verbose_name='Mode de paiement')),
                ('payment_type', models.CharField(choices=[('INITIAL', 'Initial'), ('CHARGE', 'Extra Charge'), ('FINAL', 'Final')], default='INITIAL', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='management.hotelbooking', verbose_name='Réservation')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='management.hotelshift', verbose_name='Shift de caisse')),
            ],
            options={
                'verbose_name': 'Paiement Hôtelier',
                'verbose_name_plural': 'Paiements Hôteliers',
                'ordering': ['-created_at'],
            },
        ),
    ]
