# Generated by Django 6.0.3 on 2026-05-27 17:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_remove_hotelbooking_extra_charges'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi'), (7, 'Dimanche')], verbose_name='Jour de la semaine')),
                ('start_time', models.TimeField(verbose_name="Heure d'arrivée prévue")),
                ('end_time', models.TimeField(verbose_name='Heure de départ prévue')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Planning Collaborateur',
                'verbose_name_plural': 'Plannings Collaborateurs',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('employee', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date du jour')),
                ('clock_in', models.DateTimeField(blank=True, null=True, verbose_name="Heure d'arrivée")),
                ('clock_out', models.DateTimeField(blank=True, null=True, verbose_name='Heure de départ')),
                ('break_start', models.DateTimeField(blank=True, null=True, verbose_name='Début de pause')),
                ('break_end', models.DateTimeField(blank=True, null=True, verbose_name='Fin de pause')),
                ('status', models.CharField(choices=[('PRESENT', 'Présent'), ('LATE', 'En Retard'), ('ON_BREAK', 'En Pause'), ('CLOCK_OUT', 'Parti'), ('ABSENT', 'Absent')], default='PRESENT', max_length=20)),
                ('is_late', models.BooleanField(default=False, verbose_name='Arrivé en retard')),
                ('late_minutes', models.PositiveIntegerField(default=0, verbose_name='Minutes de retard')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observations / Justification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pointage Collaborateur',
                'verbose_name_plural': 'Pointages Collaborateurs',
                'ordering': ['-date', '-clock_in'],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Titre de la tâche')),
                ('description', models.TextField(verbose_name='Détails de la consigne')),
                ('due_date', models.DateField(verbose_name="Date d'échéance")),
                ('status', models.CharField(choices=[('PENDING', 'En Attente'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name="Date/Heure d'achèvement")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_tasks', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tâche Collaborateur',
                'verbose_name_plural': 'Tâches Collaborateurs',
                'ordering': ['due_date', '-created_at'],
            },
        ),
    ]
