# Generated by Django 6.0.3 on 2026-05-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_employee_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeattendance',
            name='latitude_in',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude Arrivée'),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='longitude_in',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude Arrivée'),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='latitude_out',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude Départ'),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='longitude_out',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude Départ'),
        ),
    ]
