# Generated by Django 6.0.3 on 2026-05-27 18:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_attendance_geolocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=50, verbose_name="Type d'action")),
                ('description', models.TextField(verbose_name="Détails de l'action")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date/Heure de l'action")),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_action_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trace de Collaborateur',
                'verbose_name_plural': 'Traces de Collaborateurs',
                'ordering': ['-created_at'],
            },
        ),
    ]
