# Generated by Django 6.0.3 on 2026-05-30 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_hotelroom_synced_property_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='is_from_portal',
            field=models.BooleanField(default=False, verbose_name='Réservation Web'),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='portal_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_hotel_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Client du Portail (LogerTogo)'),
        ),
    ]
