# Generated by Django 6.0.3 on 2026-04-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_adsconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Paramètres SEO Globaux', max_length=255)),
                ('header_scripts', models.TextField(blank=True, help_text='Google Analytics, Pixel Facebook, etc.', verbose_name="Scripts de l'en-tête (Head)")),
                ('footer_scripts', models.TextField(blank=True, help_text='Scripts de chat, tracking, etc.', verbose_name='Scripts de pied de page (Body)')),
                ('meta_description', models.TextField(blank=True, verbose_name='Méta Description par défaut')),
                ('meta_keywords', models.CharField(blank=True, max_length=500, verbose_name='Méta Keywords')),
            ],
            options={
                'verbose_name': 'Paramètres SEO & Scripts',
                'verbose_name_plural': 'Paramètres SEO & Scripts',
            },
        ),
    ]
