# Generated by Django 5.1.6 on 2026-04-25 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_adsconfig_id_alter_advertisement_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Grille Tarifaire Loger Togo', max_length=255)),
                ('boost_popup_price', models.DecimalField(decimal_places=0, default=5000, max_digits=10, verbose_name='Prix Boost Pop-up (FCFA)')),
                ('boost_infeed_price', models.DecimalField(decimal_places=0, default=3000, max_digits=10, verbose_name='Prix Boost In-Feed (FCFA)')),
                ('boost_top_banner_price', models.DecimalField(decimal_places=0, default=7000, max_digits=10, verbose_name='Prix Boost Bannière Top (FCFA)')),
                ('listing_sale_price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Prix Publication Vente (FCFA)')),
                ('listing_rent_price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Prix Publication Location (FCFA)')),
                ('listing_furnished_price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Prix Publication Meublé (FCFA)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration des Prix',
                'verbose_name_plural': 'Configuration des Prix',
            },
        ),
        migrations.CreateModel(
            name='SiteAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre/Sujet')),
                ('content', models.TextField(verbose_name='Contenu (Supporte HTML/JS)')),
                ('announcement_type', models.CharField(choices=[('TICKER', 'Bandeau défilant (Ticker)'), ('POPUP', 'Alerte Pop-up')], default='TICKER', max_length=10)),
                ('is_active', models.BooleanField(default=True, verbose_name="Activer l'annonce")),
                ('background_color', models.CharField(default='#198754', max_length=20, verbose_name='Couleur de fond (Hex)')),
                ('text_color', models.CharField(default='#ffffff', max_length=20, verbose_name='Couleur du texte (Hex)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Annonce du Site (Ticker/Alerte)',
                'verbose_name_plural': 'Annonces du Site (Ticker/Alerte)',
            },
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='location',
            field=models.CharField(choices=[('TOP', 'Haut de page'), ('BOTTOM', 'Bas de page'), ('BETWEEN_LISTINGS', 'Entre les annonces (In-Feed)'), ('POPUP', 'Pop-up promotionnel'), ('POP_UNDER', 'Pop-under (Nouvel onglet)'), ('SIDEBAR', 'Barre latérale (Sidebar)'), ('STICKY_FOOTER', 'Barre flottante (Sticky Footer)')], default='TOP', max_length=20),
        ),
    ]
