# Generated by Django 5.1.6 on 2026-04-25 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_pricingconfig_siteannouncement_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PricingConfig',
        ),
    ]
