# Generated by Django 6.0.3 on 2026-04-06 11:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solvable', '0007_alter_incidentreport_incident_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='status',
            field=models.CharField(choices=[('PAID', 'Payé à temps'), ('LATE', 'Payé en retard'), ('UNPAID', 'Impayé'), ('REPORTED', 'Signalé (Litige en cours)')], default='PAID', max_length=20),
        ),
        migrations.CreateModel(
            name='MediationMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_from_mediator', models.BooleanField(default=False, verbose_name='Envoyé par le médiateur DigitalH')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mediation_messages', to='solvable.incidentreport')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mediation_messages', to='solvable.paymenthistory')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediation_sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
