# Generated by Django 6.0.3 on 2026-04-07 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solvable', '0008_alter_paymenthistory_status_mediationmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='beneficiary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_incident_claims', to=settings.AUTH_USER_MODEL, verbose_name='Bénéficiaire final de la dette'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='evidence_file',
            field=models.FileField(blank=True, null=True, upload_to='incident_evidence/', verbose_name='Document de preuve (Obligatoire)'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='is_validated',
            field=models.BooleanField(default=False, verbose_name="Validé par l'Admin"),
        ),
    ]
