# Generated by Django 5.1.6 on 2026-04-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solvable', '0010_incidentreport_notifier_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100, unique=True, verbose_name='Nom du service')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix (FCFA)')),
                ('description', models.TextField(blank=True, verbose_name="Description pour l'utilisateur")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Paramétrage Tarif',
                'verbose_name_plural': 'Paramétrage Tarifs',
            },
        ),
    ]
