# Generated by Django 6.0.3 on 2026-04-11 13:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solvable', '0011_platformpricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(verbose_name="Message de l'alerte")),
                ('display_type', models.CharField(choices=[('BANNER', 'Bandeau Fixe (Haut)'), ('MARQUEE', 'Message Défilant'), ('POPUP', 'Pop-up (Centre)'), ('TOAST', 'Notification "Push" (Style)')], default='BANNER', max_length=20)),
                ('theme', models.CharField(choices=[('URGENCY', 'Urgence (Rouge)'), ('WARNING', 'Attention (Orange)'), ('INFO', 'Information (Bleu)'), ('SUCCESS', 'Succès (Vert)')], default='URGENCY', max_length=20)),
                ('is_active', models.BooleanField(default=True, verbose_name="Activer l'alerte")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alerte Système',
                'verbose_name_plural': 'Alertes Système',
            },
        ),
    ]
