# Fichier regroupant les données de choix pour les annonces

PROPERTY_TYPE_CHOICES = [
    ('STUDIO', 'Studio'),
    ('APPARTEMENT', 'Appartement'),
    ('CHAMBRE', 'Chambre'),
    ('IMMEUBLE', 'Immeuble'),
    ('TERRAIN', 'Terrain'),
    ('PARCELLES', 'Parcelles'),
    ('VILLA', 'Villa'),
    ('MAISON', 'Maison'),
]

CITY_CHOICES = [
    ('LOME', 'Lomé (Grand Lomé)'),
    ('KARA', 'Kara'),
    ('SOKODE', 'Sokodé'),
    ('ATAKPAME', 'Atakpamé'),
    ('KPALIME', 'Kpalimé'),
    ('TSEVIE', 'Tsévié'),
    ('ANEHO', 'Aného'),
    ('DAPAONG', 'Dapaong'),
    ('VOGAN', 'Vogan'),
    ('TABLIGBO', 'Tabligbo'),
    ('NOTSE', 'Notsé'),
    ('BADOU', 'Badou'),
    ('AMLAME', 'Amlamé'),
    ('KANDE', 'Kandé'),
    ('NIAMTOUGOU', 'Niamtougou'),
    ('BASSAR', 'Bassar'),
    ('BAFILO', 'Bafilo'),
    ('TCHAMBA', 'Tchamba'),
    ('SOTOUBOUA', 'Sotouboua'),
    ('BLITTA', 'Blitta'),
    ('MANGO', 'Mango'),
    ('SANGUERA', 'Sanguéra'),
    ('BAGUIDA', 'Baguida'),
]

AMENITIES_CHOICES = [
    ('WIFI', 'WiFi'),
    ('POOL', 'Piscine'),
    ('GYM', 'Salle de sport / Gym'),
    ('GARAGE', 'Garage / Parking'),
    ('AC', 'Climatisation'),
    ('SECURITY', 'Gardiennage / Sécurité'),
    ('GENERATOR', 'Groupe électrogène'),
    ('WATER_TANK', 'Réservoir d\'eau / Surpresseur'),
    ('TV_CABLE', 'TV par câble'),
    ('WASHING_MACHINE', 'Machine à laver'),
    ('DRYER', 'Sèche-linge'),
    ('MICROWAVE', 'Micro-ondes'),
    ('REFRIGERATOR', 'Réfrigérateur'),
    ('SAUNA', 'Sauna'),
    ('LAWN', 'Pelouse / Jardin'),
    ('OUTDOOR_SHOWER', 'Douche extérieure'),
    ('WINDOW_COVERINGS', 'Stores / Rideaux'),
]

COUNTRY_CHOICES = [
    ('TG', 'Togo'),
    ('SN', 'Togo'),
    ('BJ', 'Bénin'),
    ('CI', 'Côte d\'Ivoire'),
    ('BF', 'Burkina Faso'),
    ('NE', 'Niger'),
    ('GH', 'Ghana'),
    ('FR', 'France'),
    ('ML', 'Mali'),
    ('GN', 'Guinée'),
    ('MR', 'Mauritanie'),
    ('GM', 'Gambie'),
    ('CM', 'Cameroun'),
    ('GA', 'Gabon'),
    ('MA', 'Maroc'),
    ('TN', 'Tunisie'),
    ('US', 'États-Unis'),
    ('CA', 'Canada'),
    ('ES', 'Espagne'),
    ('IT', 'Italie'),
    ('OTHER', 'Autre'),
]


