# Generated by Django 6.0.3 on 2026-03-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logersn', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(choices=[('LOME', 'Lomé'), ('THIES', 'Thiès'), ('SAINT_LOUIS', 'Saint-Louis'), ('ZIGUINCHOR', 'Ziguinchor'), ('DIOURBEL', 'Diourbel'), ('LOUGA', 'Louga'), ('FATICK', 'Fatick'), ('KAOLACK', 'Kaolack'), ('KOLDA', 'Kolda'), ('TAMBACOUNDA', 'Tambacounda'), ('MATAM', 'Matam'), ('KAFFRINE', 'Kaffrine'), ('KEDOUGOU', 'Kédougou'), ('SEDHIOU', 'Sédhiou')], default='LOME', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('APARTMENT', 'Appartement'), ('VILLA', 'Villa'), ('STUDIO', 'Studio'), ('COMMERCIAL', 'Local Commercial')], max_length=20),
        ),
    ]
