# Generated by Django 6.0.3 on 2026-04-06 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logersn', '0006_alter_property_bedrooms_alter_property_has_garage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='air_conditioning',
            field=models.BooleanField(default=False, verbose_name='Climatisation'),
        ),
        migrations.AddField(
            model_name='property',
            name='generator',
            field=models.BooleanField(default=False, verbose_name='Groupe électrogène'),
        ),
        migrations.AddField(
            model_name='property',
            name='gym',
            field=models.BooleanField(default=False, verbose_name='Salle de sport'),
        ),
        migrations.AddField(
            model_name='property',
            name='microwave',
            field=models.BooleanField(default=False, verbose_name='Micro-ondes'),
        ),
        migrations.AddField(
            model_name='property',
            name='refrigerator',
            field=models.BooleanField(default=False, verbose_name='Réfrigérateur'),
        ),
        migrations.AddField(
            model_name='property',
            name='swimming_pool',
            field=models.BooleanField(default=False, verbose_name='Piscine'),
        ),
        migrations.AddField(
            model_name='property',
            name='tv_cable',
            field=models.BooleanField(default=False, verbose_name='TV par câble'),
        ),
        migrations.AddField(
            model_name='property',
            name='washing_machine',
            field=models.BooleanField(default=False, verbose_name='Machine à laver'),
        ),
        migrations.AddField(
            model_name='property',
            name='water_tank',
            field=models.BooleanField(default=False, verbose_name="Réservoir d'eau"),
        ),
        migrations.AddField(
            model_name='property',
            name='wifi',
            field=models.BooleanField(default=False, verbose_name='WiFi'),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(choices=[('LOME', 'Lomé'), ('THIES', 'Thiès'), ('MBOUR', 'Mbour'), ('SALY', 'Saly'), ('TOUBA', 'Touba'), ('RUFISQUE', 'Rufisque'), ('SAINT_LOUIS', 'Saint-Louis'), ('ZIGUINCHOR', 'Ziguinchor'), ('DIOURBEL', 'Diourbel'), ('LOUGA', 'Louga'), ('FATICK', 'Fatick'), ('KAOLACK', 'Kaolack'), ('KOLDA', 'Kolda'), ('TAMBACOUNDA', 'Tambacounda'), ('MATAM', 'Matam'), ('KAFFRINE', 'Kaffrine'), ('KEDOUGOU', 'Kédougou'), ('SEDHIOU', 'Sédhiou'), ('SINE_SALOUM', 'Sine Saloum')], default='LOME', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='neighborhood',
            field=models.CharField(choices=[('ALMADIES', 'Almadies'), ('ALMADIES_2', 'Almadies 2'), ('AMITIÉ', 'Amitié'), ('AVENUE_BOURGUIBA', 'Avenue Bourguiba'), ('BAMBELOR', 'Bambelor'), ('BAMBEY', 'Bambey'), ('BARGNY', 'Bargny'), ('BAYAKH', 'Bayakh'), ('BEL_AIR', 'Bel air'), ('BEN_TALY', 'Ben Taly'), ('BISCUITERIE', 'Biscuiterie'), ('BOPP', 'Bopp'), ('CAMBÉRÈNE', 'Cambérène'), ('CASTOR', 'Castor'), ('CENTENAIRE', 'Centenaire'), ('CITE_MOURTADA', 'CITE MOURTADA'), ('CITÉ_ASECNA', 'Cité asecna'), ('CITÉ_ASSEMBLÉE', 'Cité assemblée'), ('CITÉ_AVION', 'Cité avion'), ('CITÉ_BATRAIN', 'Cité Batrain'), ('CITÉ_BIAGUI', 'Cité biagui'), ('CITÉ_CHECK_AMAR', 'Cité Check Amar'), ('CITÉ_DAMEL', 'Cité Damel'), ('CITÉ_KEUR_GORGUI', 'Cité keur gorgui'), ('CITÉ_LITTORAL', 'Cité littoral'), ('CITÉ_MBAKIYOU_FAYE', 'Cité Mbakiyou Faye'), ('CITÉ_MIXTA', 'Cité mixta'), ('COLOBANE', 'Colobane'), ('COMICO', 'Comico'), ('DALIFORT', 'Dalifort'), ('DERKLE', 'Derkle'), ('DIAMAGUENE', 'Diamaguene'), ('DIAMALAYE', 'Diamalaye'), ('DIAMNIADIO', 'Diamniadio'), ('DIASS', 'Diass'), ('DIAXAY', 'Diaxay'), ('DIENDER', 'Diender'), ('DIEUPPEUL', 'Dieuppeul'), ('DIOFIOR', 'Diofior'), ('DJIDAH_THIAROYE_KAW', 'Djidah thiaroye kaw'), ('DJILOR', 'Djilor'), ('DJILY_MBAYE', 'Djily mbaye'), ('FANDENE', 'Fandene'), ('FANN', 'Fann'), ('FANN_HOCK', 'Fann hock'), ('FASS', 'Fass'), ('FASS_KAOLACK', 'Fass Kaolack'), ('FENÊTRE_MERMOZ', 'Fenêtre Mermoz'), ('FISSEL', 'Fissel'), ('FOIRE', 'Foire'), ('FOUNDIOUGNE', 'Foundiougne'), ('GADAYE', 'Gadaye'), ('GANDIAYE', 'Gandiaye'), ('GANDIGAL', 'Gandigal'), ('GIBRALTAR', 'Gibraltar'), ('GOLF', 'Golf'), ('GOROM', 'Gorom'), ('GORÉE', 'Gorée'), ('GOSSAS', 'Gossas'), ('GRAND_LOME', 'Grand-Lomé'), ('GRAND_MBAO', 'Grand mbao'), ('GRAND_YOFF', 'Grand yoff'), ('GUEDIAWAYE', 'Guediawaye'), ('GUEREO', 'Guereo'), ('GUEULE_TAPÉE', 'Gueule-tapée'), ('GUINAW_RAIL', 'Guinaw rail'), ('GUINGUINEO', 'Guinguineo'), ('HANN', 'Hann'), ('HANN_BEL_AIR', 'Hann bel air'), ('HANN_MARINAS', 'Hann marinas'), ('HANN_MARISTE', 'Hann mariste'), ('HLM', 'HLM'), ('HLM_GRAND_MEDINE', 'HLM GRAND MEDINE'), ('HLM_GRAND_YOFF', 'HLM grand yoff'), ('JOAL_FADIOUTH', 'Joal fadiouth'), ('KAHONE', 'Kahone'), ('KAOLACK', 'Kaolack'), ('KARACK', 'Karack'), ('KARRANG_POSTE', 'Karrang poste'), ('KAYAR', 'Kayar'), ('KEUR_MADIABEL', 'Keur madiabel'), ('KEUR_MASSAR', 'Keur massar'), ('KEUR_MOUSSA', 'Keur Moussa'), ('KEUR_NDIAYE_LO', 'Keur Ndiaye lo'), ('KHAR_YALLA', 'Khar yalla'), ('KHOMBOLE', 'Khombole'), ('KOUNOUNE', 'Kounoune'), ('LAC_ROSE', 'Lac rose'), ('LIBERTÉ_1', 'Liberté 1'), ('LIBERTÉ_2', 'Liberté 2'), ('LIBERTÉ_3', 'Liberté 3'), ('LIBERTÉ_4', 'Liberté 4'), ('LIBERTÉ_5', 'Liberté 5'), ('LIBERTÉ_6', 'Liberté 6'), ('LIBERTÉ_6_EXTENSION', 'Liberté 6 extension'), ('MALIBOUNDA', 'Malibounda'), ('MALIBU', 'Malibu'), ('MALIKA', 'Malika'), ('MAMELLES', 'Mamelles'), ('MARISTE', 'Mariste'), ('MARISTE_2', 'Mariste 2'), ('MBACKE', 'Mbacke'), ('MBAO', 'Mbao'), ('MBODIENE', 'Mbodiene'), ('MBORO', 'Mboro'), ('MBOSS', 'Mboss'), ('MECKHE', 'Meckhe'), ('MEDINA', 'Medina'), ('MERMOZ', 'Mermoz'), ('MERMOZ_SACRÉ_COEUR', 'Mermoz-Sacré Coeur'), ('MONUMENT_RENAISSANCE', 'Monument renaissance'), ('NDAYANE', 'Ndayane'), ('NDIAGNIAO', 'Ndiagniao'), ('NDIAKHIRATE', 'Ndiakhirate'), ('NDOFFANE', 'Ndoffane'), ('NGAPAROU', 'Ngaparou'), ('NGOR', 'Ngor'), ('NGOUNDIANE', 'Ngoundiane'), ('NGUEKHOKH', 'Nguekhokh'), ('NGUENIENE', 'Ngueniene'), ('NGUERING', 'Nguering'), ('NIAGUE', 'Niague'), ('NIAKOUL_RAP', 'Niakoul rap'), ('NIANING', 'Nianing'), ('NIARY_TALY', 'Niary taly'), ('NIORO_DU_RIP', 'Nioro du rip'), ('NOFLAYE', 'Noflaye'), ('NORD_FOIRE', 'Nord foire'), ('NOTO', 'Noto'), ('OUAGOU_NIAYE', 'Ouagou niaye'), ('OUAKAM', 'Ouakam'), ('OUAKAM_BRIOCHE_DORÉE', 'Ouakam brioche dorée'), ('OUAKAM_MONPRIX', 'OUAKAM MONPRIX'), ('OUEST_FOIRE', 'Ouest foire'), ('OUKAM_CORNICHE', 'Oukam Corniche'), ('PARCELLES_ASSAINIES', 'Parcelles assainies'), ('PASSI', 'Passi'), ('PATTE_D_OIE', "Patte d'oie"), ('PIKINE', 'Pikine'), ('PLATEAU', 'Plateau'), ('POINTE_SARENE', 'Pointe sarene'), ('POINT_E', 'Point E'), ('POPENGUINE', 'Popenguine'), ('POUT', 'Pout'), ('RUFISQUE', 'Rufisque'), ('SACRÉ_CŒUR_1', 'Sacré cœur 1'), ('SACRÉ_CŒUR_2', 'Sacré cœur 2'), ('SACRÉ_CŒUR_3', 'Sacré cœur 3'), ('SALY_PORTUDAL', 'Saly portudal'), ('SANDIARA', 'Sandiara'), ('SANGALKAM', 'Sangalkam'), ('SCAT_URBAM', 'Scat urbam'), ('SEBIKOTANE', 'Sebikotane'), ('SENDOU', 'Sendou'), ('SESSENE', 'Sessene'), ('SIBASSOR', 'Sibassor'), ('SICAP_BAOBAB', 'Sicap baobab'), ('SICAP_FOIRE', 'Sicap foire'), ('SICAP_LIBERTÉ', 'Sicap liberté'), ('SICAP_MBAO', 'Sicap mbao'), ('SICAP_SACRÉ_CŒUR', 'Sicap sacré cœur'), ('SINDIA', 'Sindia'), ('SIPRES', 'Sipres'), ('SOKONE', 'Sokone'), ('SOMONE', 'Somone'), ('SOUM', 'Soum'), ('SUD_FOIRE', 'Sud foire'), ('TASSETTE', 'Tassette'), ('THIADIAYE', 'Thiadiaye'), ('THIAROYE', 'Thiaroye'), ('THIENABA', 'Thienaba'), ('THONGOR', 'Thongor'), ('TIVAOUANE_PEULH', 'Tivaouane peulh'), ('TIVAOUANE_THIES', 'Tivaouane thies'), ('TOUBAB_DIALO', 'Toubab dialo'), ('TOUBACOUTA', 'Toubacouta'), ('TOUBA_TOUL', 'Touba toul'), ('VDN', 'VDN'), ('VIRAGE', 'Virage'), ('WARANG', 'Warang'), ('YENE', 'Yene'), ('YEUMBEUL', 'Yeumbeul'), ('YOFF', 'Yoff'), ('ZAC_MBAO', 'Zac mbao'), ('ZONE_A', 'Zone A'), ('ZONE_B', 'Zone B'), ('ZONE_DE_CAPTAGE', 'Zone de captage'), ('ZONE_INDUSTRIELLE', 'Zone industrielle')], max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('APARTMENT', 'Appartement'), ('APARTMENT_F3', 'Appartement F3'), ('APARTMENT_F4', 'Appartement F4'), ('APARTMENT_F5', 'Appartement F5'), ('CHAMBRE_SDB_INTERNE', 'Chambre salle de bain interne'), ('CHAMBRE_SIMPLE', 'Chambre simple'), ('COLOCATION', 'Colocation'), ('STUDIO', 'Studio'), ('MINI_STUDIO', 'Mini studio'), ('STUDIO_SEPARE', 'Studio séparé'), ('STUDIO_ENTREE_SALON', 'Studio entrée salon'), ('STUDIO_AMERICAIN', 'Studio américain'), ('MINI_STUDIO_AMERICAIN', 'Mini studio américain'), ('MAISON', 'Maison'), ('VILLA', 'Villa'), ('DUPLEX', 'Duplex'), ('TRIPLEX', 'Triplex'), ('IMMEUBLE', 'Immeuble'), ('TERRAIN', 'Terrain'), ('COMMERCIAL', 'Local Commercial'), ('BOUTIQUE', 'Boutique'), ('MAGASIN', 'Magasin'), ('BUREAU', 'Bureau'), ('SHOWROOM', 'Showroom'), ('USAGE_PRO', 'Usage professionnel')], max_length=50),
        ),
    ]
