# Generated by Django 6.0.3 on 2026-04-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logersn', '0009_pricingconfig_property_boost_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='days',
            field=models.IntegerField(default=1, verbose_name='Nombre de jours'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('PUBLICATION', 'Frais de Publication'), ('BOOST', "Boost d'Annonce"), ('POPUP', 'Mise en avant Pop-up')], max_length=20),
        ),
    ]
