# Generated by Django 6.0.3 on 2026-04-07 00:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logersn', '0011_property_latitude_property_longitude_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='rent_price',
        ),
        migrations.AddField(
            model_name='property',
            name='listing_category',
            field=models.CharField(choices=[('RENT', 'A louer'), ('SALE', 'A vendre'), ('FURNISHED', 'Meublé')], default='RENT', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix (CFA)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='price_per_night',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix par nuitée (Meublé)'),
        ),
        migrations.CreateModel(
            name='PropertyEquipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Ex: Réfrigérateur, Climatiseur, TV...', max_length=100)),
                ('brand', models.CharField(blank=True, help_text='Marque optionnelle', max_length=100, null=True)),
                ('icon_class', models.CharField(default='fa-plug', help_text='Icône FontAwesome (ex: fa-tv, fa-snowflake)', max_length=50)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interior_equipments', to='logersn.property')),
            ],
        ),
    ]
