# Generated by Django 6.0.3 on 2026-04-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logersn', '0012_remove_property_rent_price_property_listing_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingconfig',
            name='publication_fee',
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='publication_fee_furnished',
            field=models.DecimalField(decimal_places=2, default=300.0, max_digits=10, verbose_name='Prix Publication (Meublé)'),
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='publication_fee_rent',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10, verbose_name='Prix Publication (Location)'),
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='publication_fee_sale',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10, verbose_name='Prix Publication (Vente)'),
        ),
    ]
