# Generated by Django 5.1.6 on 2026-04-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logersn', '0015_alter_database_charset'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='has_balcony',
            field=models.BooleanField(blank=True, default=False, verbose_name='Balcon'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_courtyard',
            field=models.BooleanField(blank=True, default=False, verbose_name='Cour'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_garden',
            field=models.BooleanField(blank=True, default=False, verbose_name='Jardin'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_terrace',
            field=models.BooleanField(blank=True, default=False, verbose_name='Terrasse'),
        ),
        migrations.AddField(
            model_name='property',
            name='kitchens',
            field=models.IntegerField(blank=True, default=0, verbose_name='Nombre de cuisines'),
        ),
        migrations.AddField(
            model_name='property',
            name='salons',
            field=models.IntegerField(blank=True, default=0, verbose_name='Nombre de salons'),
        ),
    ]
