# Generated by Django 5.1.6 on 2026-04-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logersn', '0017_alter_favorite_id_alter_pricingconfig_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='document_type',
            field=models.CharField(blank=True, choices=[('BAIL', 'BAIL'), ('TITRE_FONCIER_INDIVIDUEL', 'TITRE FONCIER INDIVIDUEL'), ('TITRE_FONCIER_GLOBAL', 'TITRE FONCIER GLOBAL'), ('ACTE_DE_VENTE', 'ACTE DE VENTE'), ('DELIBERATION', 'DELIBERATION')], max_length=50, null=True, verbose_name='Type de document'),
        ),
        migrations.AddField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='boost_daily_fee',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=20, verbose_name='Prix Boost par jour'),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='popup_daily_fee',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=20, verbose_name='Prix Pop-up par jour'),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='publication_fee_furnished',
            field=models.DecimalField(decimal_places=2, default=300.0, max_digits=20, verbose_name='Prix Publication (Meublé)'),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='publication_fee_rent',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=20, verbose_name='Prix Publication (Location)'),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='publication_fee_sale',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=20, verbose_name='Prix Publication (Vente)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(choices=[('LOME', 'Lomé (Grand Lomé)'), ('KARA', 'Kara'), ('SOKODE', 'Sokodé'), ('ATAKPAME', 'Atakpamé'), ('KPALIME', 'Kpalimé'), ('TSEVIE', 'Tsévié'), ('ANEHO', 'Aného'), ('DAPAONG', 'Dapaong'), ('VOGAN', 'Vogan'), ('TABLIGBO', 'Tabligbo'), ('NOTSE', 'Notsé'), ('BADOU', 'Badou'), ('AMLAME', 'Amlamé'), ('KANDE', 'Kandé'), ('NIAMTOUGOU', 'Niamtougou'), ('BASSAR', 'Bassar'), ('BAFILO', 'Bafilo'), ('TCHAMBA', 'Tchamba'), ('SOTOUBOUA', 'Sotouboua'), ('BLITTA', 'Blitta'), ('MANGO', 'Mango'), ('SANGUERA', 'Sanguéra'), ('BAGUIDA', 'Baguida')], default='LOME', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='neighborhood',
            field=models.CharField(choices=[('ABLOGAMÉ', 'Ablogamé'), ('ADAMAVO', 'Adamavo'), ('ADIDOGOMÉ', 'Adidogomé'), ('AFLAO', 'Aflao'), ('AGBADJAHONOU', 'Agbadjahonou'), ('AGBALÉPÉDOGAN', 'Agbalépédogan'), ('AGBONOU', 'Agbonou'), ('AGOÈ_ASSIYÉYÉ', 'Agoè-Assiyéyé'), ('AGOÈ_NYIVÉ', 'Agoè-Nyivé'), ('AKODÉSSÉWA', 'Akodésséwa'), ('AMADAHOMÉ', 'Amadahomé'), ('AMOUTIÉVÉ', 'Amoutiévé'), ('ATIKOUMÉ', 'Atikoumé'), ('ATTIÉGOU', 'Attiégou'), ('AVÉDJI', 'Avédji'), ('BAGUIDA', 'Baguida'), ('BÈ', 'Bè'), ('BÈ_KPOTA', 'Bè-Kpota'), ('CACAVÉLI', 'Cacavéli'), ('CENTRE_VILLE', 'Centre-Ville'), ('CHAMINADE', 'Chaminade'), ('DECKON', 'Deckon'), ('DJIDJOLÉ', 'Djidjolé'), ('DJIFA_KPOTA', 'Djifa-Kpota'), ('DZOGBÉGAN', 'Dzogbégan'), ('FOREVER', 'Forever'), ('GBLINKOMÉ', 'Gblinkomé'), ('GBÉTSOGBÉ', 'Gbétsogbé'), ('GNAGNA', 'Gnagna'), ('HANOUKOPÉ', 'Hanoukopé'), ('HEDZRANAWOÉ', 'Hedzranawoé'), ('HÉDZRANAWOÉ_2', 'Hédzranawoé 2'), ('KAMINA', 'Kamina'), ('KANGNI_KOPÉ', 'Kangni-Kopé'), ('KARA_NORD', 'Kara-Nord'), ('KARA_SUD', 'Kara-Sud'), ('KATANGA', 'Katanga'), ('KLIKAMÉ', 'Klikamé'), ('KODJOVIAKOPÉ', 'Kodjoviakopé'), ('KOMAH', 'Komah'), ('KOULOUNDÈ', 'Kouloundè'), ('KPODJI', 'Kpodji'), ('KÉGUÉ', 'Kégué'), ('KÉLÉGOUGAN', 'Kélégougan'), ('LASSA', 'Lassa'), ('LOGOPÉ', 'Logopé'), ('LÉGBASSITO', 'Légbassito'), ('MABOULÉ', 'Maboulé'), ('NUKAFU', 'Nukafu'), ('NYÉKONAKPOÉ', 'Nyékonakpoé'), ('PÉRIPHÉRIE', 'Périphérie'), ('RÉSIDENCE_DU_BÉNIN', 'Résidence du Bénin'), ('SANGUÉRA', 'Sanguéra'), ('SOUZA_NÉTIMÉ', 'Souza-Nétimé'), ('TCHAOUDJO', 'Tchaoudjo'), ('TOKOIN', 'Tokoin'), ('TOMDÈ', 'Tomdè'), ('TOTSI', 'Totsi'), ('UNIVERSITÉ', 'Université'), ('VAKPOSSITO', 'Vakpossito'), ('ZOMAYI', 'Zomayi'), ('ZONE_INDUSTRIELLE', 'Zone Industrielle'), ('ZONE_RÉSIDENTIELLE', 'Zone Résidentielle'), ('ZONGO', 'Zongo')], max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Prix (CFA)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_per_night',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Prix par nuitée (Meublé)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
