# Generated by Django 5.1.6 on 2026-04-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logersn', '0018_property_document_type_property_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='neighborhood',
            field=models.CharField(max_length=100, verbose_name='Quartier'),
        ),
    ]
