# Generated by Django 5.1.6 on 2026-04-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logersn', '0019_alter_property_neighborhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='floor_level',
            field=models.IntegerField(blank=True, default=0, verbose_name="Niveau d'étage"),
        ),
        migrations.AddField(
            model_name='property',
            name='households',
            field=models.IntegerField(blank=True, default=0, verbose_name='Nombre de ménages'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('STUDIO', 'Studio'), ('APPARTEMENT', 'Appartement'), ('CHAMBRE', 'Chambre'), ('IMMEUBLE', 'Immeuble'), ('TERRAIN', 'Terrain'), ('PARCELLES', 'Parcelles'), ('VILLA', 'Villa'), ('MAISON', 'Maison')], max_length=50),
        ),
    ]
