# Generated by Django 5.1.6 on 2026-04-22 23:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logersn', '0020_property_floor_level_property_households_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 étoile'), (2, '2 étoiles'), (3, '3 étoiles'), (4, '4 étoiles'), (5, '5 étoiles')], verbose_name='Note (1-5)')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name="Titre de l'avis")),
                ('comment', models.TextField(verbose_name='Commentaire')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approuvé (visible)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='logersn.property')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis & Notations',
                'ordering': ['-created_at'],
                'unique_together': {('property', 'reviewer')},
            },
        ),
    ]
