# Generated by Django 5.1.6 on 2026-04-22 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logersn', '0021_add_property_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('city', models.CharField(blank=True, choices=[('LOME', 'Lomé (Grand Lomé)'), ('KARA', 'Kara'), ('SOKODE', 'Sokodé'), ('ATAKPAME', 'Atakpamé'), ('KPALIME', 'Kpalimé'), ('TSEVIE', 'Tsévié'), ('ANEHO', 'Aného'), ('DAPAONG', 'Dapaong'), ('VOGAN', 'Vogan'), ('TABLIGBO', 'Tabligbo'), ('NOTSE', 'Notsé'), ('BADOU', 'Badou'), ('AMLAME', 'Amlamé'), ('KANDE', 'Kandé'), ('NIAMTOUGOU', 'Niamtougou'), ('BASSAR', 'Bassar'), ('BAFILO', 'Bafilo'), ('TCHAMBA', 'Tchamba'), ('SOTOUBOUA', 'Sotouboua'), ('BLITTA', 'Blitta'), ('MANGO', 'Mango'), ('SANGUERA', 'Sanguéra'), ('BAGUIDA', 'Baguida')], default='', max_length=100, verbose_name='Ville')),
                ('property_type', models.CharField(blank=True, choices=[('STUDIO', 'Studio'), ('APPARTEMENT', 'Appartement'), ('CHAMBRE', 'Chambre'), ('IMMEUBLE', 'Immeuble'), ('TERRAIN', 'Terrain'), ('PARCELLES', 'Parcelles'), ('VILLA', 'Villa'), ('MAISON', 'Maison')], default='', max_length=50, verbose_name='Type de bien')),
                ('listing_category', models.CharField(blank=True, choices=[('', 'Toutes'), ('RENT', 'Location'), ('SALE', 'Vente'), ('FURNISHED', 'Meublé')], default='', max_length=20, verbose_name='Catégorie')),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Budget max (FCFA)')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Token désabonnement')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alerte Immobilière',
                'verbose_name_plural': 'Alertes Immobilières (Abonnements)',
            },
        ),
    ]
