# Generated by Django 5.1.6 on 2026-04-25 03:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logersn', '0022_add_property_alert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingconfig',
            name='popup_daily_fee',
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='boost_infeed_fee',
            field=models.DecimalField(decimal_places=0, default=3000, max_digits=20, verbose_name='Boost In-Feed (par jour)'),
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='boost_popup_fee',
            field=models.DecimalField(decimal_places=0, default=5000, max_digits=20, verbose_name='Boost Pop-up (par jour)'),
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='boost_top_banner_fee',
            field=models.DecimalField(decimal_places=0, default=7000, max_digits=20, verbose_name='Boost Top Banner (par jour)'),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='boost_daily_fee',
            field=models.DecimalField(decimal_places=0, default=1000, max_digits=20, verbose_name='Boost Standard (par jour)'),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='publication_fee_furnished',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='Prix Publication (Meublé)'),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='publication_fee_rent',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='Prix Publication (Location)'),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='publication_fee_sale',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='Prix Publication (Vente)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='listing_category',
            field=models.CharField(choices=[('RENT', 'En location'), ('SALE', 'En vente'), ('FURNISHED', 'Meublé')], default='RENT', max_length=20),
        ),
        migrations.CreateModel(
            name='PropertyApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, verbose_name='Message / Motivation')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('ACCEPTED', 'Acceptée'), ('REJECTED', 'Refusée')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='logersn.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
                'unique_together': {('property', 'tenant')},
            },
        ),
    ]
