# Generated by Django 5.1.6 on 2026-04-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logersn', '0023_remove_pricingconfig_popup_daily_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('STUDIO', 'Studio'), ('APPARTEMENT', 'Appartement'), ('CHAMBRE', 'Chambre'), ('IMMEUBLE', 'Immeuble'), ('TERRAIN', 'Terrain'), ('PARCELLES', 'Parcelles'), ('VILLA', 'Villa'), ('MAISON', 'Maison'), ('HOTEL', 'Hôtel'), ('AUBERGE', 'Auberge'), ('MUSEE', 'Musée'), ('BUSINESS', 'Espace Business / Bureau')], max_length=50),
        ),
        migrations.AlterField(
            model_name='propertyalert',
            name='property_type',
            field=models.CharField(blank=True, choices=[('STUDIO', 'Studio'), ('APPARTEMENT', 'Appartement'), ('CHAMBRE', 'Chambre'), ('IMMEUBLE', 'Immeuble'), ('TERRAIN', 'Terrain'), ('PARCELLES', 'Parcelles'), ('VILLA', 'Villa'), ('MAISON', 'Maison'), ('HOTEL', 'Hôtel'), ('AUBERGE', 'Auberge'), ('MUSEE', 'Musée'), ('BUSINESS', 'Espace Business / Bureau')], default='', max_length=50, verbose_name='Type de bien'),
        ),
    ]
