# Generated by Django 5.1.6 on 2026-04-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logersn', '0024_alter_property_property_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(choices=[('LOME', 'Lomé (Grand Lomé)'), ('KARA', 'Kara'), ('SOKODE', 'Sokodé'), ('ATAKPAME', 'Atakpamé'), ('KPALIME', 'Kpalimé'), ('TSEVIE', 'Tsévié'), ('ANEHO', 'Aného'), ('DAPAONG', 'Dapaong'), ('VOGAN', 'Vogan'), ('TABLIGBO', 'Tabligbo'), ('NOTSE', 'Notsé'), ('BADOU', 'Badou'), ('AMLAME', 'Amlamé'), ('KANDE', 'Kandé'), ('NIAMTOUGOU', 'Niamtougou'), ('BASSAR', 'Bassar'), ('BAFILO', 'Bafilo'), ('TCHAMBA', 'Tchamba'), ('SOTOUBOUA', 'Sotouboua'), ('BLITTA', 'Blitta'), ('MANGO', 'Mango'), ('SANGUERA', 'Sanguéra'), ('BAGUIDA', 'Baguida')], db_index=True, default='LOME', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='listing_category',
            field=models.CharField(choices=[('RENT', 'En location'), ('SALE', 'En vente'), ('FURNISHED', 'Meublé')], db_index=True, default='RENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('STUDIO', 'Studio'), ('APPARTEMENT', 'Appartement'), ('CHAMBRE', 'Chambre'), ('IMMEUBLE', 'Immeuble'), ('TERRAIN', 'Terrain'), ('PARCELLES', 'Parcelles'), ('VILLA', 'Villa'), ('MAISON', 'Maison'), ('HOTEL', 'Hôtel'), ('AUBERGE', 'Auberge'), ('MUSEE', 'Musée'), ('BUSINESS', 'Espace Business / Bureau')], db_index=True, max_length=50),
        ),
    ]
