# Generated by Django 6.0.4 on 2026-05-05 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logersn', '0025_alter_property_city_alter_property_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='document_type',
            field=models.CharField(blank=True, choices=[('BAIL', 'Bail'), ('TITRE_FONCIER_INDIVIDUEL', 'Titre Foncier Individuel'), ('TITRE_FONCIER_GLOBAL', 'Titre Foncier Global'), ('ACTE_DE_VENTE', 'Acte de Vente'), ('DELIBERATION', 'Délibération')], max_length=50, null=True, verbose_name='Type de document'),
        ),
    ]
