# Generated by Django 6.0.4 on 2026-05-06 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logersn', '0027_property_discount_percentage_property_discount_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='advance_months',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name="Mois d'avance"),
        ),
        migrations.AddField(
            model_name='property',
            name='agency_fee_months',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name="Mois de frais d'agence"),
        ),
        migrations.AddField(
            model_name='property',
            name='deposit_months',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Mois de caution'),
        ),
        migrations.AddField(
            model_name='property',
            name='visit_fee',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Frais de visite (CFA)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='document_type',
            field=models.CharField(blank=True, choices=[('BAIL', 'Bail'), ('TITRE_FONCIER_INDIVIDUEL', 'Titre Foncier Individuel'), ('TITRE_FONCIER_GLOBAL', 'Titre Foncier Global'), ('ACTE_COUTUMIER', 'Acte Coutumier'), ('DEUX_TAMPONS', '2 Tampons'), ('TROIS_TAMPONS', '3 Tampons')], max_length=50, null=True, verbose_name='Type de document'),
        ),
    ]
