# Generated by Django 6.0.3 on 2026-05-07 00:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logersn', '0028_property_advance_months_property_agency_fee_months_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['listing_category', 'is_published'], name='logersn_pro_listing_9a444c_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type'], name='logersn_pro_propert_532a03_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city', 'neighborhood'], name='logersn_pro_city_930b90_idx'),
        ),
    ]
