# Generated by Django 6.0.3 on 2026-05-07 01:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logersn', '0029_property_logersn_pro_listing_9a444c_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_boosted'], name='logersn_pro_is_boos_720711_idx'),
        ),
    ]
