# Generated by Django 6.0.4 on 2026-05-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logersn', '0030_add_is_boosted_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='document_type',
            field=models.CharField(blank=True, choices=[('TITRE_FONCIER_INDIVIDUEL', 'Titre foncier individuel'), ('TITRE_FONCIER_GLOBAL', 'Titre foncier global'), ('BAIL', 'Bail'), ('ACTE_DE_VENTE', 'Acte de vente'), ('PAPIER_COUTUMIER', 'Papier coutumier'), ('DEUX_TAMPONS', '2 Tampons'), ('TROIS_TAMPONS', '3 Tampons'), ('NONE', 'Aucun / Autre')], max_length=50, null=True, verbose_name='Type de document'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('UNE_PIECE', 'Une pièce'), ('CHAMBRE_SALON', 'Chambre salon'), ('DEUX_CHAMBRES_SALON', '2 chambres salon'), ('TROIS_CHAMBRES_SALON', '3 chambres salon'), ('STUDIO', 'Studio'), ('APPARTEMENT', 'Appartement'), ('CHAMBRE', 'Chambre'), ('IMMEUBLE', 'Immeuble'), ('TERRAIN', 'Terrain'), ('PARCELLES', 'Parcelles'), ('VILLA', 'Villa'), ('MAISON', 'Maison'), ('HOTEL', 'Hôtel'), ('AUBERGE', 'Auberge'), ('MUSEE', 'Musée'), ('BUSINESS', 'Espace Business / Bureau')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='propertyalert',
            name='property_type',
            field=models.CharField(blank=True, choices=[('UNE_PIECE', 'Une pièce'), ('CHAMBRE_SALON', 'Chambre salon'), ('DEUX_CHAMBRES_SALON', '2 chambres salon'), ('TROIS_CHAMBRES_SALON', '3 chambres salon'), ('STUDIO', 'Studio'), ('APPARTEMENT', 'Appartement'), ('CHAMBRE', 'Chambre'), ('IMMEUBLE', 'Immeuble'), ('TERRAIN', 'Terrain'), ('PARCELLES', 'Parcelles'), ('VILLA', 'Villa'), ('MAISON', 'Maison'), ('HOTEL', 'Hôtel'), ('AUBERGE', 'Auberge'), ('MUSEE', 'Musée'), ('BUSINESS', 'Espace Business / Bureau')], default='', max_length=50, verbose_name='Type de bien'),
        ),
    ]
