# Generated by Django 6.0.4 on 2026-05-14 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logersn', '0031_alter_property_document_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingCampaignTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du modèle')),
                ('subject', models.CharField(max_length=255, verbose_name='Objet par défaut')),
                ('content', models.TextField(verbose_name='Contenu HTML')),
            ],
            options={
                'verbose_name': 'Modèle de Campagne',
                'verbose_name_plural': 'Modèles de Campagnes',
            },
        ),
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name="Objet de l'e-mail")),
                ('content', models.TextField(help_text='Utilisez [PRENOM] ou [NOM] pour personnaliser.', verbose_name='Contenu (HTML supporté)')),
                ('recipient_group', models.CharField(choices=[('ALL', 'Tous les utilisateurs'), ('AGENTS', 'Agences immobilières'), ('OWNERS', 'Particuliers (Bailleurs)'), ('TENANTS', 'Locataires / Chercheurs'), ('VERIFIED', 'Professionnels Vérifiés uniquement')], default='ALL', help_text='Ignoré si des destinataires individuels sont sélectionnés.', max_length=20, verbose_name='Groupe de destinataires')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True, verbose_name='Planifié pour')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Envoyé')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi réel")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('individual_recipients', models.ManyToManyField(blank=True, related_name='targeted_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Destinataires individuels')),
                ('template', models.ForeignKey(blank=True, help_text='Si sélectionné, le sujet et le contenu seront pré-remplis (vous pourrez les modifier).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='logersn.marketingcampaigntemplate', verbose_name='Utiliser un modèle')),
            ],
            options={
                'verbose_name': 'Campagne Marketing',
                'verbose_name_plural': 'Campagnes Marketing',
            },
        ),
    ]
