# Generated by Django 6.0.3 on 2026-05-22 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logersn', '0032_marketingcampaigntemplate_marketingcampaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_authorized_by_admin',
            field=models.BooleanField(default=False, verbose_name="Autorisé par l'administrateur"),
        ),
        migrations.AddField(
            model_name='property',
            name='publication_requested',
            field=models.BooleanField(default=False, verbose_name='Demande de publication'),
        ),
    ]
