# Generated by Django 6.0.4 on 2026-05-23 03:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logersn', '0033_property_is_authorized_by_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='advance_months',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Mois d'avance"),
        ),
        migrations.AlterField(
            model_name='property',
            name='agency_fee_months',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Mois de frais d'agence"),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nombre de chambres'),
        ),
        migrations.AlterField(
            model_name='property',
            name='deposit_months',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Mois de caution'),
        ),
        migrations.AlterField(
            model_name='property',
            name='floor_level',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Niveau d'étage"),
        ),
        migrations.AlterField(
            model_name='property',
            name='households',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nombre de ménages'),
        ),
        migrations.AlterField(
            model_name='property',
            name='kitchens',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nombre de cuisines'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix (CFA)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_per_night',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix par nuitée (Meublé)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='salons',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nombre de salons'),
        ),
        migrations.AlterField(
            model_name='property',
            name='surface',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Surface (m2)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='toilets',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nombre de toilettes'),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_rooms',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nombre total de pièces'),
        ),
        migrations.AlterField(
            model_name='property',
            name='visit_fee',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Frais de visite (CFA)'),
        ),
    ]
