# Generated by Django 6.0.4 on 2026-05-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logersn', '0034_alter_property_advance_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price_unit',
            field=models.CharField(choices=[('month', 'mensuel'), ('night', 'nuitée'), ('hour', 'heure'), ('total', 'Prix Total')], default='month', max_length=20, verbose_name='Unité de tarification'),
        ),
    ]
