# Generated by Django 6.0.3 on 2026-07-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logersn', '0035_property_price_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='visible_on_portal',
            field=models.BooleanField(default=True, verbose_name='Visible sur LogerTogo'),
        ),
    ]
