"""
Django settings for Logertogo project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-fallback-for-local-dev-only')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ['157.180.127.70', 'logertogo.com', 'www.logertogo.com', 'localhost', '127.0.0.1']
SITE_URL = 'https://logertogo.com'

# Security & SSL Configuration (Senior Production Setup)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = False
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
CSRF_TRUSTED_ORIGINS = [
    'https://logertogo.com',
    'https://www.logertogo.com',
]
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'django.contrib.sites',
    'django.contrib.postgres',
    'django.contrib.humanize',  # {% load humanize %} → intcomma, naturaltime...
    
    # Third-party
    'rest_framework',
    'corsheaders',
    'storages',
    'drf_spectacular',

    # Local apps
    'users',
    'logersn',
    'chat',
    'ads',
    'management',
    'blog',
]

SITE_ID = 1
# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# CORS Configuration
CORS_ALLOW_ALL_ORIGINS = True  # Utile pour le développement mobile
CORS_ALLOW_CREDENTIALS = True




AUTH_USER_MODEL = 'users.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'logertogo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                'ads.context_processors.ads_processor',
                'logersn.context_processors.google_maps_api_key',
            ],
            # Rend property_tags et humanize disponibles dans TOUS les templates
            # sans besoin de {% load ... %}
            'builtins': [
                'logersn.templatetags.property_tags',
                'django.contrib.humanize.templatetags.humanize',
            ],
        },
    },
]

WSGI_APPLICATION = 'logertogo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Database override for production
db_url = os.environ.get('DATABASE_URL')
if db_url:
    DATABASES = {
        'default': dj_database_url.parse(db_url)
    }
    DATABASES['default']['CONN_MAX_AGE'] = 600
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

print(f"Database Engine: {DATABASES['default'].get('ENGINE', 'Postgres/Custom')}")


AUTHENTICATION_BACKENDS = [
    'users.backends.PhoneOrEmailBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'users.validators.ComplexPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'Africa/Lome'

USE_I18N = True

USE_TZ = True

LANGUAGES = [
    ('fr', 'Français'),
    ('en', 'English'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Cloudflare R2 / S3 Storage Configuration
USE_S3 = os.environ.get('USE_S3', 'False') == 'True'

if USE_S3:
    AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_ENDPOINT_URL = os.environ.get('AWS_S3_ENDPOINT_URL') # ex: https://<account_id>.r2.cloudflarestorage.com
    AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'auto')
    AWS_S3_CUSTOM_DOMAIN = os.environ.get('AWS_S3_CUSTOM_DOMAIN') # ex: media.logertogo.com
    
    AWS_DEFAULT_ACL = None
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    AWS_S3_ADDRESSING_STYLE = 'path'
    AWS_QUERYSTRING_AUTH = False
    AWS_S3_FILE_OVERWRITE = False
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',
    }
    
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
        },
    }
    # Configuration des URLs de média pour S3
    if USE_S3:
        if AWS_S3_CUSTOM_DOMAIN:
            MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/'
        else:
            MEDIA_URL = f'{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/'
else:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
        },
    }
    MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'

# WhiteNoise settings
WHITENOISE_INDEX_FILE = False
WHITENOISE_MANIFEST_STRICT = False
WHITENOISE_KEEP_ONLY_HASHED_FILES = True
WHITENOISE_MAX_AGE = 31536000  # 1 an pour le cache navigateur

# Email Configuration (Direct Server O2switch / SMTP local)
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ.get('EMAIL_HOST', 'localhost')
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 25))
    EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'False') == 'True'
    EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'False') == 'True'
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'contact@logertogo.com')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_PASSWORD', '')
    EMAIL_TIMEOUT = 10
DEFAULT_FROM_EMAIL = 'Loger Togo <contact@logertogo.com>'
SERVER_EMAIL = 'contact@logertogo.com'

# Configuration FedaPay / DigitalH
# (Les paramètres MEDIA_URL et MEDIA_ROOT sont définis plus haut)

# Auth Settings
AUTHENTICATION_BACKENDS = [
    'users.backends.PhoneOrEmailBackend',
    'django.contrib.auth.backends.ModelBackend',
]
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'home'



# Spectacular Settings (Point 8)
SPECTACULAR_SETTINGS = {
    'TITLE': 'Loger Togo API',
    'DESCRIPTION': 'Documentation technique des services immobiliers de prestige par DigitalH.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# --- SMS API CONFIGURATION (TERMII) ---
TERMII_API_KEY = os.environ.get('TERMII_API_KEY', '')
TERMII_SENDER_ID = os.environ.get('TERMII_SENDER_ID', 'Loger Togo')

# --- GOOGLE MAPS CONFIGURATION ---
GOOGLE_MAPS_API_KEY = 'AIzaSyA_GfKlf9j2JIgDApRr2HikBZzMw0PqrcU'

# --- CONFIGURATION LOCALE (ZÉRO CONFLIT) ---
# Ce bloc permet de surcharger les réglages (comme la BDD) sur le serveur
try:
    from .local_settings import *
except ImportError:
    pass

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- CACHE CONFIGURATION (Haute Performance) ---
# Utilisation de DatabaseCache pour la persistance si Redis n'est pas présent
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'django_cache_table',
        'TIMEOUT': 3600,  # 1 heure par défaut
    }
}
# Table de cache à créer via: python manage.py createcachetable

# --- SECURITY & HSTS (SEO & Trust) ---
if not DEBUG:
    # La redirection SSL est gérée par Apache (.htaccess) pour plus de stabilité.
    SECURE_SSL_REDIRECT = False 
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # HSTS : Informe le navigateur de toujours utiliser HTTPS
    SECURE_HSTS_SECONDS = 31536000 # 1 an (Standard SEO)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'

# --- PWA CONFIGURATION ---
PWA_APP_NAME = 'Loger Togo'
PWA_APP_SHORT_NAME = 'LogerTogo'
PWA_APP_DESCRIPTION = "Plateforme d'Immobilier de Confiance au Togo"
PWA_APP_THEME_COLOR = '#0b4629'
PWA_APP_BACKGROUND_COLOR = '#ffffff'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'any'
PWA_APP_START_URL = '/'
PWA_APP_STATUS_BAR_COLOR = 'default'
PWA_APP_ICONS = [
    {
        'src': '/static/img/icon-192x192.png',
        'sizes': '192x192'
    },
    {
        'src': '/static/img/icon-512x512.png',
        'sizes': '512x512'
    }
]
PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR, 'static', 'serviceworker.js')

JAZZMIN_SETTINGS = {
    "site_title": "Loger Togo Admin",
    "site_header": "Loger Togo",
    "site_brand": "Loger Togo",
    "site_logo": "img/logo_square.png",
    "welcome_sign": "Bienvenue sur l'administration de Loger Togo",
    "copyright": "Loger Togo",
    "search_model": ["users.User", "logersn.Property"],
    "topmenu_links": [
        {"name": "Dashboard",  "url": "admin:index"},
        {"name": "Statistiques Réelles", "url": "/admin/statistiques/", "permissions": ["users.view_user"], "new_window": False},
        {"name": "Voir le site", "url": "/", "new_window": True},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "icons": {
        "auth": "fas fa-users-cog",
        "users.User": "fas fa-user",
        "logersn.Property": "fas fa-building",
        "logersn.PropertyEquipment": "fas fa-couch",
    },
    "default_icon_children": "fas fa-circle",
}

JAZZMIN_UI_TWEAKS = {
    "brand_colour": "navbar-success",
    "accent": "accent-success",
    "navbar": "navbar-success navbar-dark",
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-success",
    "theme": "lumen",
    "button_classes": {
        "primary": "btn-success",
        "secondary": "btn-outline-secondary",
        "success": "btn-success"
    }
}
